set(PROJECT_NAME "StaticLib2")

set(CMAKE_GLOBAL_AUTOGEN_TARGET OFF)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

file(GLOB StaticLib2_SOURCE_FILES
  "${CMAKE_CURRENT_SOURCE_DIR}/*.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
)
source_group(
  TREE ${CMAKE_CURRENT_SOURCE_DIR}
  PREFIX Source
  FILES ${StaticLib2_SOURCE_FILES}
)

if(OS_WINDOWS)
  add_library(${PROJECT_NAME} STATIC ${StaticLib2_SOURCE_FILES})
endif() # OS_WINDOWS